import type { VideoDataSubtitle } from "@vot.js/core/types/client";
import { normalizeLang } from "@vot.js/shared/utils/utils";
import type { MinimalVideoData } from "../types/client";
import { BaseHelper, VideoHelperError } from "./base";

export default class JoveHelper extends BaseHelper {
  // eslint-disable-next-line @typescript-eslint/require-await
  async getVideoId(url: URL) {
    const match = /^\/(?:[a-z]{2}\/)?v\/(\d+)\/([^/?#]+)/i.exec(url.pathname);
    return match ? `v/${match[1]}/${match[2]}` : undefined;
  }

  async getVideoData(videoId: string): Promise<MinimalVideoData | undefined> {
    if (!videoId) return undefined;

    let nextData: any;
    if (typeof window !== "undefined" && typeof document !== "undefined") {
      const nextDataEl = document.getElementById("__NEXT_DATA__");
      if (nextDataEl?.textContent) {
        try {
          nextData = JSON.parse(nextDataEl.textContent);
        } catch (err: any) {
          throw new VideoHelperError(
            `Failed to parse DOM __NEXT_DATA__: ${err.message}`,
          );
        }
      }
    }

    const queries = nextData?.props?.pageProps?.dehydratedState?.queries || [];
    let extracted: any;

    for (const q of queries) {
      const data = q.state?.data;
      if (!data) continue;

      for (const target of [data.domain, data]) {
        const videoObj = target?.videos?.en;
        if (videoObj?.cdnFile) {
          extracted = {
            videoUrl: videoObj.cdnFile,
            duration: videoObj.lengthSeconds
              ? parseInt(videoObj.lengthSeconds, 10)
              : undefined,
            title: target.title,
            description: target.titleDescription,
            subtitles: videoObj.subtitles,
          };
          break;
        }
      }
      if (extracted) break;
    }

    if (!extracted?.videoUrl) {
      throw new VideoHelperError(`Failed to retrieve video URL for ${videoId}`);
    }

    const {
      videoUrl,
      duration,
      title,
      description,
      subtitles: subtitlesObj,
    } = extracted;

    const subtitles: VideoDataSubtitle[] = subtitlesObj
      ? Object.entries(subtitlesObj)
          .filter(([, url]) => typeof url === "string")
          .map(([lang, url]) => ({
            language: normalizeLang(lang),
            source: "jove",
            format: "vtt",
            url: url as string,
            isAutoGenerated: false,
          }))
      : [];

    return {
      url: `https://www.jove.com/${videoId}`,
      video_url: videoUrl,
      title,
      description,
      duration,
      subtitles,
      translationHelp: [
        {
          target: "video_file_url",
          targetUrl: videoUrl,
        },
      ],
    } as MinimalVideoData & { video_url: string };
  }
}
