import { config } from "@vot.js/shared";
import Logger from "@vot.js/shared/utils/logger";
import { normalizeLang } from "@vot.js/shared/utils/utils";
import type { MinimalVideoData } from "../types/client";
import type * as Loom from "../types/helpers/loom";
import { BaseHelper, VideoHelperError } from "./base";

const CAPTION_FIELDS = `
  __typename
  ... on VideoTranscriptDetails {
    language captions_source_url captions_url
    captionsInOriginalLanguage captionsTranslatedLanguage
    captionsTranslationInProgress captionTranslationErrorFallback
    transcription_status processing_service
  }
  ... on InvalidRequestWarning { message }
  ... on GenericError { message }
`;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function getLoomAssetUrls(html: string): {
  runtimeUrl?: string;
  captionLanguagesUrl?: string;
} {
  const scripts = [
    ...html.matchAll(
      /<script\b[^>]*\bsrc\s*=\s*(["'])(https:\/\/cdn\.loom\.com\/.*?)\1[^>]*>/gi,
    ),
  ].map(([, , url]) => url);

  return {
    runtimeUrl: scripts.find((url) => /\/0runtime-[^/]+\.js$/.test(url)),
    captionLanguagesUrl: scripts.find((url) => /\/44073-[^/]+\.js$/.test(url)),
  };
}

export function parseLoomClientVersion(runtime: string): string {
  const version = runtime.match(
    /SENTRY_RELEASE\s*=\s*\{\s*id\s*:\s*["']([^"']+)["']/,
  )?.[1];
  if (!version) throw new Error("Failed to find Loom client version");
  return version;
}

export function parseLoomCaptionLanguages(bundle: string): string[] {
  const languageMap = /L4:\{([^}]+)\},Yj:/.exec(bundle)?.[1];
  if (!languageMap) throw new Error("Failed to find Loom caption languages");

  const languages = [
    ...languageMap.matchAll(/(?:^|,)([a-z]{2,3}):"((?:\\.|[^"\\])*)"/g),
  ]
    .filter(([, code, label]) => code !== "unknown" && label !== code)
    .map(([, code]) => code);
  if (!languages.length) throw new Error("Loom caption language list is empty");
  return languages;
}

export function parseLoomCaptionTrack(
  value: unknown,
  requestedLanguage?: string,
): Loom.LoomCaptionTrack | undefined {
  if (!isRecord(value) || value.__typename !== "VideoTranscriptDetails") {
    return undefined;
  }

  const transcript = value as unknown as Loom.VideoTranscriptDetails;
  const translatedLanguage =
    typeof transcript.captionsTranslatedLanguage === "string"
      ? transcript.captionsTranslatedLanguage
      : undefined;
  const isOriginal =
    typeof transcript.captionsInOriginalLanguage === "boolean"
      ? transcript.captionsInOriginalLanguage
      : !translatedLanguage || translatedLanguage === transcript.language;
  if (
    transcript.captionsTranslationInProgress ||
    (!isOriginal && transcript.captionTranslationErrorFallback) ||
    (transcript.transcription_status &&
      transcript.transcription_status !== "success")
  ) {
    return undefined;
  }

  const language = isOriginal
    ? transcript.language
    : translatedLanguage || requestedLanguage;
  const captionsPath = isOriginal
    ? transcript.captions_source_url || transcript.captions_url
    : transcript.captions_source_url;
  if (!language || !captionsPath) return undefined;
  const cleanLanguage = language.trim();
  if (!cleanLanguage) return undefined;

  try {
    const captionsUrl = new URL(captionsPath, "https://cdn.loom.com/");
    if (captionsUrl.protocol !== "https:") return undefined;
    return {
      language: cleanLanguage,
      captionsUrl: captionsUrl.href,
      isAutoGenerated:
        transcript.processing_service === "instant_whisper" || !isOriginal,
    };
  } catch {
    return undefined;
  }
}

export default class LoomHelper extends BaseHelper {
  async getVideoData(videoId: string): Promise<MinimalVideoData | undefined> {
    const shareBaseUrl = this.service?.url ?? "https://www.loom.com/share/";
    const shareUrl = `${shareBaseUrl}${encodeURIComponent(videoId)}`;

    try {
      const page = await this.fetch(shareUrl, {
        headers: { Accept: "text/html" },
      });
      if (!page.ok) {
        throw new VideoHelperError(`Failed to load Loom page (${page.status})`);
      }

      const assets = getLoomAssetUrls(await page.text());
      if (!assets.runtimeUrl || !assets.captionLanguagesUrl) {
        throw new VideoHelperError("Failed to find Loom caption assets");
      }
      const [runtimeResponse, languageResponse] = await Promise.all([
        this.fetch(assets.runtimeUrl),
        this.fetch(assets.captionLanguagesUrl),
      ]);
      if (!runtimeResponse.ok || !languageResponse.ok) {
        throw new VideoHelperError("Failed to load Loom caption assets");
      }

      const [runtime, bundle] = await Promise.all([
        runtimeResponse.text(),
        languageResponse.text(),
      ]);
      const version = parseLoomClientVersion(runtime);
      const languages = parseLoomCaptionLanguages(bundle);
      const data = await this.fetchCaptionData(videoId, version, languages);
      const original = parseLoomCaptionTrack(data.original);
      if (!original)
        throw new VideoHelperError("Loom captions are unavailable");

      const tracks = [
        original,
        ...languages.flatMap((language, index) => {
          const track = parseLoomCaptionTrack(
            data[`caption_${index}`],
            language,
          );
          return track &&
            normalizeLang(track.language) === normalizeLang(language)
            ? [track]
            : [];
        }),
      ];
      const subtitles: NonNullable<MinimalVideoData["subtitles"]> = [];
      const seen = new Set<string>();
      for (const track of tracks) {
        const language = normalizeLang(track.language);
        if (!language || seen.has(language)) continue;
        seen.add(language);
        subtitles.push({
          format: "vtt",
          language,
          source: "loom",
          url: track.captionsUrl,
          isAutoGenerated: track.isAutoGenerated,
        });
      }
      return { url: shareUrl, subtitles };
    } catch (error) {
      Logger.error(
        `Failed to get Loom video data, because: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
      return this.returnBaseData(videoId);
    }
  }

  private async fetchCaptionData(
    videoId: string,
    version: string,
    languages: string[],
  ): Promise<Loom.LoomCaptionData> {
    const operationName = "GetAllLoomCaptions";
    const selections = [
      `original: fetchVideoTranscript(
        videoId: $videoId,
        password: null,
        captionsLanguageSelection: null
      ) { ${CAPTION_FIELDS} }`,
      ...languages.map(
        (language, index) =>
          `caption_${index}: fetchVideoTranscript(
            videoId: $videoId,
            password: null,
            captionsLanguageSelection: ${JSON.stringify(language)}
          ) { ${CAPTION_FIELDS} }`,
      ),
    ].join("\n");
    const response = await this.fetch("https://www.loom.com/graphql", {
      method: "POST",
      headers: {
        "User-Agent": config.userAgent,
        "content-type": "application/json",
        "x-loom-request-source": `loom_web_${version}`,
        "apollographql-client-name": "web",
        "apollographql-client-version": version,
        "Alt-Used": "www.loom.com",
      },
      body: JSON.stringify({
        operationName,
        variables: { videoId },
        query: `query ${operationName}($videoId: ID!) { ${selections} }`,
      }),
      signal: AbortSignal.timeout(15_000),
    });
    if (!response.ok) {
      throw new VideoHelperError(
        `Failed to query Loom captions (${response.status})`,
      );
    }

    const { data } = (await response.json()) as {
      data?: Loom.LoomCaptionData;
    };
    if (!data) throw new VideoHelperError("Loom returned no caption data");
    return data;
  }

  // eslint-disable-next-line @typescript-eslint/require-await
  async getVideoId(url: URL) {
    return /(embed|share)\/([^/]+)?/.exec(url.pathname)?.[2];
  }
}
