import type { GraphQL } from "@vot.js/shared/types/utils";

export type SentryRelease = {
  id: string;
};

export type VideoTranscriptDetails = {
  id?: number;
  video_id?: string;
  captions_source_url?: string;
  captions_url?: string;
  language?: string;
  captionsInOriginalLanguage?: boolean;
  captionsTranslatedLanguage?: string | null;
  captionsTranslationInProgress?: boolean;
  captionTranslationErrorFallback?: boolean;
  transcription_status?: string;
  processing_service?: string;
  __typename: "VideoTranscriptDetails";
};

export type GenericError = {
  message: string;
  __typename: "GenericError";
};

export type InvalidRequestWarning = {
  message?: string;
  __typename: "InvalidRequestWarning";
};

export type VideoTranscriptResult =
  | VideoTranscriptDetails
  | GenericError
  | InvalidRequestWarning;

export type VideoTranscriptData = Record<
  "fetchVideoTranscript",
  VideoTranscriptDetails | GenericError
>;

export type VideoTranscript = GraphQL<VideoTranscriptData>;

export type LoomCaptionData = Record<string, VideoTranscriptResult>;

export type LoomCaptionTrack = {
  language: string;
  captionsUrl: string;
  isAutoGenerated: boolean;
};